// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CourseNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseNumber = 110,
                            Credits = 4,
                            Description = "Introduction to systematic program design using a functional programming language. Focuses on problem solving, abstraction, and data-driven design.",
                            SubjectCode = "CPSC",
                            Title = "Computation, Programs, and Programming"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseNumber = 121,
                            Credits = 4,
                            Description = "Introduction to formal models of computation, including logic, proofs, and abstract machines. Emphasizes reasoning about program correctness.",
                            SubjectCode = "CPSC",
                            Title = "Models of Computation"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseNumber = 210,
                            Credits = 4,
                            Description = "Design and construction of large software systems with emphasis on modularity, abstraction, testing, and documentation.",
                            SubjectCode = "CPSC",
                            Title = "Software Construction"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseNumber = 213,
                            Credits = 4,
                            Description = "Introduction to computer organization, operating systems concepts, memory hierarchy, and low-level programming.",
                            SubjectCode = "CPSC",
                            Title = "Computer Systems"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseNumber = 221,
                            Credits = 4,
                            Description = "Design and analysis of fundamental data structures and algorithms including lists, trees, graphs, and algorithmic complexity.",
                            SubjectCode = "CPSC",
                            Title = "Basic Algorithms and Data Structures"
                        },
                        new
                        {
                            CourseId = 6,
                            CourseNumber = 211,
                            Credits = 4,
                            Description = "Introduction to digital logic, computer organization, and low-level programming with emphasis on hardware–software interaction.",
                            SubjectCode = "CPEN",
                            Title = "Computing Systems I"
                        },
                        new
                        {
                            CourseId = 7,
                            CourseNumber = 212,
                            Credits = 4,
                            Description = "Continuation of CPEN 211 covering advanced computer architecture, pipelines, memory systems, and parallelism.",
                            SubjectCode = "CPEN",
                            Title = "Computing Systems II"
                        },
                        new
                        {
                            CourseId = 8,
                            CourseNumber = 221,
                            Credits = 3,
                            Description = "Matrices, systems of linear equations, determinants, vector spaces, eigenvalues, and applications to engineering problems.",
                            SubjectCode = "MATH",
                            Title = "Matrix Algebra"
                        },
                        new
                        {
                            CourseId = 9,
                            CourseNumber = 220,
                            Credits = 3,
                            Description = "Introduction to mathematical reasoning and proof techniques including induction, contradiction, and formal logic.",
                            SubjectCode = "MATH",
                            Title = "Mathematical Proof"
                        },
                        new
                        {
                            CourseId = 10,
                            CourseNumber = 251,
                            Credits = 3,
                            Description = "Basic statistical methods including probability, random variables, estimation, hypothesis testing, and data analysis.",
                            SubjectCode = "STAT",
                            Title = "Elementary Statistics"
                        });
                });

            modelBuilder.Entity("Backend.Models.CourseOffering", b =>
                {
                    b.Property<int>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfferingId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfferingId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseOfferings");

                    b.HasData(
                        new
                        {
                            OfferingId = 1,
                            CourseId = 1,
                            Section = "001",
                            Term = "2024W"
                        },
                        new
                        {
                            OfferingId = 2,
                            CourseId = 1,
                            Section = "002",
                            Term = "2024W"
                        },
                        new
                        {
                            OfferingId = 3,
                            CourseId = 3,
                            Section = "101",
                            Term = "2024W"
                        },
                        new
                        {
                            OfferingId = 4,
                            CourseId = 3,
                            Section = "201",
                            Term = "2025S"
                        },
                        new
                        {
                            OfferingId = 5,
                            CourseId = 5,
                            Section = "001",
                            Term = "2024W"
                        },
                        new
                        {
                            OfferingId = 6,
                            CourseId = 6,
                            Section = "001",
                            Term = "2024W"
                        },
                        new
                        {
                            OfferingId = 7,
                            CourseId = 7,
                            Section = "001",
                            Term = "2025S"
                        });
                });

            modelBuilder.Entity("Backend.Models.CourseOfferingMeeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeetingId"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("MeetingId");

                    b.HasIndex("OfferingId");

                    b.ToTable("CourseOfferingMeetings");

                    b.HasData(
                        new
                        {
                            MeetingId = 1,
                            Day = 0,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            Location = "DMP 201",
                            OfferingId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = 0
                        },
                        new
                        {
                            MeetingId = 2,
                            Day = 2,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            Location = "DMP 201",
                            OfferingId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = 0
                        },
                        new
                        {
                            MeetingId = 3,
                            Day = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            Location = "ANGU 098",
                            OfferingId = 2,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Type = 0
                        },
                        new
                        {
                            MeetingId = 4,
                            Day = 0,
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            Location = "ICCS 236",
                            OfferingId = 3,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Type = 0
                        },
                        new
                        {
                            MeetingId = 5,
                            Day = 3,
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            Location = "ICCS 236",
                            OfferingId = 3,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Type = 0
                        },
                        new
                        {
                            MeetingId = 6,
                            Day = 4,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            Location = "EOS 120",
                            OfferingId = 5,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = 0
                        },
                        new
                        {
                            MeetingId = 7,
                            Day = 1,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Location = "KAIS 1010",
                            OfferingId = 6,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Type = 2
                        },
                        new
                        {
                            MeetingId = 8,
                            Day = 0,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            Location = "CHBE 102",
                            OfferingId = 7,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Type = 0
                        });
                });

            modelBuilder.Entity("Backend.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("integer");

                    b.HasKey("CourseId", "PrerequisiteId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("CoursePrerequisites");

                    b.HasData(
                        new
                        {
                            CourseId = 2,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 4,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            CourseId = 5,
                            PrerequisiteId = 2
                        },
                        new
                        {
                            CourseId = 5,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            CourseId = 6,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 7,
                            PrerequisiteId = 6
                        });
                });

            modelBuilder.Entity("Backend.Models.CourseOffering", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.CourseOfferingMeeting", b =>
                {
                    b.HasOne("Backend.Models.CourseOffering", "Offering")
                        .WithMany("Meetings")
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offering");
                });

            modelBuilder.Entity("Backend.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("Backend.Models.CourseOffering", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
